/**
 * Guide library → MCP resources.
 *
 * Loads the bundled guides export (data/guides-export.json) at server
 * startup and exposes each guide as an MCP resource. The export is
 * generated by `scripts/fetch-guides.mjs` during the .mcpb build,
 * pulling from https://get.yourorbit.team/api/guides/export.
 *
 * Why this exists
 * ---------------
 * The Orbit web library (80+ long-form guides on lifecycle marketing,
 * deliverability, Braze, email craft, experimentation) is the most
 * accurate source of practitioner knowledge Orbit controls. Exposing
 * them as MCP resources lets Claude cite the exact guide that matches
 * a user's question — without a live web fetch — so answers are
 * grounded in Orbit's authored content rather than generic training data.
 *
 * Resource URIs
 * -------------
 * - orbit://guides/index            — JSON index of all guides
 * - orbit://guides/{slug}           — individual guide as markdown
 * - orbit://guides/by-category/{c}  — JSON list scoped to a category
 *
 * The index is useful for discovery — Claude can read it cheaply,
 * pick the right guide, then read just that one as markdown. This
 * keeps the working token set small while giving access to the
 * whole library on demand.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GUIDES_EXPORT_PATH = path.resolve(
  __dirname,
  "..",
  "data",
  "guides-export.json"
);

/**
 * Load the export once at startup. If the file is missing we log and
 * return null — registration becomes a no-op, the mcpb still starts,
 * the other resources and tools remain available. This keeps guides
 * as a nice-to-have rather than a hard dependency.
 */
function loadGuidesExport() {
  try {
    if (!fs.existsSync(GUIDES_EXPORT_PATH)) {
      process.stderr.write(
        "[Orbit] guides-export.json not found — guide resources will not be registered.\n"
      );
      return null;
    }
    const raw = fs.readFileSync(GUIDES_EXPORT_PATH, "utf8");
    const parsed = JSON.parse(raw);
    if (!parsed || !Array.isArray(parsed.guides)) {
      process.stderr.write(
        "[Orbit] guides-export.json is malformed — guide resources will not be registered.\n"
      );
      return null;
    }
    return parsed;
  } catch (err) {
    process.stderr.write(
      `[Orbit] Failed to load guides-export.json: ${err?.message ?? err}\n`
    );
    return null;
  }
}

/**
 * Build the index resource payload — compact metadata for every guide,
 * grouped by category. Designed to be read in full by Claude as a
 * cheap discovery step. 80 guides × ~200 bytes metadata each is ~16KB
 * — well within a reasonable resource-read budget.
 */
function buildIndex(exportPayload) {
  const byCategory = {};
  for (const g of exportPayload.guides) {
    const cat = g.category ?? "uncategorised";
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push({
      slug: g.slug,
      title: g.title,
      summary: g.summary,
      uri: `orbit://guides/${g.slug}`,
      canonicalUrl: g.canonicalUrl,
      primarySkill: g.primarySkill,
      secondarySkills: g.secondarySkills,
      targetQuery: g.targetQuery,
      readingMinutes: g.readingMinutes,
    });
  }
  return {
    version: exportPayload.version,
    exportedAt: exportPayload.exportedAt,
    count: exportPayload.count,
    categories: Object.keys(byCategory).sort(),
    guidesByCategory: byCategory,
    guides: exportPayload.guides.map((g) => ({
      slug: g.slug,
      title: g.title,
      summary: g.summary,
      category: g.category,
      uri: `orbit://guides/${g.slug}`,
      canonicalUrl: g.canonicalUrl,
    })),
  };
}

function makeMarkdownResource(uri, text) {
  // The exporter already emits a markdown title at the top of each
  // guide (# Guide title), so we pass the body through unchanged
  // rather than wrapping with a second title header.
  return {
    contents: [
      {
        uri: uri.href,
        mimeType: "text/markdown",
        text: text.trim(),
      },
    ],
  };
}

function makeJsonResource(uri, payload) {
  return {
    contents: [
      {
        uri: uri.href,
        mimeType: "application/json",
        text: JSON.stringify(payload, null, 2),
      },
    ],
  };
}

/**
 * Register every guide-related MCP resource on the given server.
 * No-ops safely if the export file is missing or malformed.
 */
export function registerGuideResources(server, { ResourceTemplate } = {}) {
  const exportPayload = loadGuidesExport();
  if (!exportPayload) return { registered: false, count: 0 };

  const index = buildIndex(exportPayload);

  // 1. The index resource — discovery surface.
  server.registerResource(
    "guides-index",
    "orbit://guides/index",
    {
      title: "Orbit Guides Index",
      description: `Index of ${index.count} long-form Orbit guides. Lists every guide by slug, title, summary, category, URI, and canonical URL. Read this first to pick the right guide for a user's question, then read the specific guide resource.`,
      mimeType: "application/json",
    },
    async (uri) => makeJsonResource(uri, index)
  );

  // 2. Per-category index — useful when Claude wants to browse a
  //    specific area (e.g. "show me deliverability guides").
  for (const category of index.categories) {
    server.registerResource(
      `guides-category-${category}`,
      `orbit://guides/by-category/${category}`,
      {
        title: `Orbit Guides — ${category}`,
        description: `All ${index.guidesByCategory[category].length} Orbit guides in the ${category} category.`,
        mimeType: "application/json",
      },
      async (uri) =>
        makeJsonResource(uri, {
          category,
          count: index.guidesByCategory[category].length,
          guides: index.guidesByCategory[category],
        })
    );
  }

  // 3. Per-guide markdown resources. Each one a first-class resource
  //    so Claude can read exactly what it needs without pulling the
  //    whole library.
  for (const guide of exportPayload.guides) {
    const uri = `orbit://guides/${guide.slug}`;
    const description =
      `${guide.summary} ` +
      `[Category: ${guide.category}. ` +
      `Related skill: ${guide.primarySkill}. ` +
      `Reading time: ${guide.readingMinutes} min. ` +
      `Canonical URL: ${guide.canonicalUrl}]`;
    server.registerResource(
      `guide-${guide.slug}`,
      uri,
      {
        title: guide.title,
        description,
        mimeType: "text/markdown",
      },
      async (u) => makeMarkdownResource(u, guide.markdown)
    );
  }

  return {
    registered: true,
    count: exportPayload.guides.length + index.categories.length + 1,
    guideCount: exportPayload.guides.length,
    categoryCount: index.categories.length,
    exportedAt: exportPayload.exportedAt,
  };
}
