import path from "node:path";
import { ensureDir, resolveOutputDir } from "./config.js";
import { renderLifecycleDiagram } from "./lifecycle-diagrams.js";
import {
  buildOrbitMarkdownFooter,
  buildOrbitMarkdownHeader,
  ensureOrbitBrandingAssets,
  getOrbitBrandingMeta
} from "./orbit-branding.js";
import { NOTION_EXPORT_SCHEMA } from "./production-specs.js";
import { maybeReadTextFile, parseJsonInput, slugify, writeJson, writeText } from "./utils.js";

export async function exportNotionBundle({
  config,
  rootDir,
  workspace,
  briefMarkdown,
  messagePlan,
  diagramSpec,
  previewManifest = [],
  outputDir
}) {
  const workspaceRecord =
    typeof workspace === "string" ? parseJsonInput(workspace, "workspace") : workspace;
  const plan =
    typeof messagePlan === "string" ? parseJsonInput(messagePlan, "message plan") : messagePlan;
  const diagram =
    typeof diagramSpec === "string" ? parseJsonInput(diagramSpec, "diagram spec") : diagramSpec;

  const programName =
    workspaceRecord?.program_name ?? plan?.program_name ?? "Orbit Program";
  const exportDir = ensureDir(
    outputDir ?? resolveOutputDir(config, "notion-exports", slugify(programName))
  );
  const branding = ensureOrbitBrandingAssets({
    rootDir,
    outputDir: exportDir
  });

  let diagramPng = null;
  if (diagram?.type === "lifecycle_diagram") {
    const rendered = await renderLifecycleDiagram({
      rootDir,
      spec: diagram,
      outputDir: exportDir,
      formats: ["png"]
    });
    diagramPng = rendered.files.png ?? rendered.files.notion_png ?? null;
  }

  const previewEntries = normalizePreviewManifest(previewManifest);
  const resolvedBrief = maybeReadTextFile(
    briefMarkdown ?? workspaceRecord?.artifacts?.brief_markdown ?? "_No brief provided._"
  );
  const indexMarkdown = buildIndexDoc({
    programName,
    workspaceRecord,
    previewEntries,
    diagramPng,
    branding
  });
  const messagePlanMarkdown = buildMessagePlanDoc(plan, branding);
  const buildChecklistMarkdown = buildChecklistDoc(plan, branding);
  const previewMarkdown = buildPreviewDoc(previewEntries, branding);
  const artifactManifest = {
    program_name: programName,
    workspace_dir: workspaceRecord?.workspace_dir ?? null,
    diagram_png: diagramPng,
    previews: previewEntries,
    generated_by: getOrbitBrandingMeta()
  };

  const files = {
    index_markdown: writeText(path.join(exportDir, "00-index.md"), indexMarkdown),
    brief_markdown: writeText(
      path.join(exportDir, "01-program-brief.md"),
      String(resolvedBrief ?? "_No brief provided._")
    ),
    message_plan_markdown: writeText(
      path.join(exportDir, "02-message-plan.md"),
      messagePlanMarkdown
    ),
    build_checklist_markdown: writeText(
      path.join(exportDir, "03-build-checklist.md"),
      buildChecklistMarkdown
    ),
    preview_manifest_markdown: writeText(
      path.join(exportDir, "04-preview-manifest.md"),
      previewMarkdown
    ),
    artifact_manifest_json: writeJson(
      path.join(exportDir, "artifact-manifest.json"),
      artifactManifest
    ),
    diagram_png: diagramPng
  };

  const bundle = {
    version: "1.0.0",
    type: "notion_export_bundle",
    program_name: programName,
    export_dir: exportDir,
    generated_by: getOrbitBrandingMeta(),
    artifacts: files
  };

  writeJson(path.join(exportDir, "notion-export.json"), bundle);

  return {
    status: "ok",
    bundle,
    schema: NOTION_EXPORT_SCHEMA
  };
}

function normalizePreviewManifest(previewManifest) {
  return (previewManifest ?? []).map((entry, index) => {
    const record =
      typeof entry === "string" ? parseJsonInput(entry, `preview manifest ${index + 1}`) : entry;
    return {
      title: record.title ?? record.name ?? `Preview ${index + 1}`,
      desktop: record.desktop ?? record.files?.desktop ?? null,
      mobile: record.mobile ?? record.files?.mobile ?? null,
      dark: record.dark ?? record.files?.dark ?? null
    };
  });
}

function buildIndexDoc({ programName, workspaceRecord, previewEntries, diagramPng, branding }) {
  return [
    buildOrbitMarkdownHeader({
      title: programName,
      subtitle: "Program documentation bundle generated by Orbit.",
      logoPath: branding?.assets?.light?.relative ?? null,
      contextLines: [
        `- Platform: ${workspaceRecord?.platform ?? "n/a"}`,
        `- Workspace: ${workspaceRecord?.workspace_dir ?? "n/a"}`
      ]
    }),
    "",
    "## Included Documents",
    "- Program brief",
    "- Message plan",
    "- Build checklist",
    "- Preview manifest",
    diagramPng ? "- Lifecycle diagram PNG" : null,
    previewEntries.length > 0 ? "- HTML preview file references" : null,
    "",
    "## Workspace Context",
    `- Platform: ${workspaceRecord?.platform ?? "n/a"}`,
    `- Workspace: ${workspaceRecord?.workspace_dir ?? "n/a"}`,
    `- Objective: ${workspaceRecord?.objective ?? "n/a"}`,
    "",
    "## Import Notes",
    "- These files are Markdown-first for clean Notion import.",
    "- Keep linked HTML previews and PNG artifacts in the same export package.",
    "- Update final ownership and build status inside Notion after import."
    ,
    buildOrbitMarkdownFooter()
  ]
    .filter(Boolean)
    .join("\n");
}

function buildMessagePlanDoc(plan, branding) {
  if (!plan) {
    return [
      buildOrbitMarkdownHeader({
        title: "Message Plan",
        subtitle: "Internal Orbit planning artifact.",
        logoPath: branding?.assets?.light?.relative ?? null
      }),
      "_No message plan supplied._",
      buildOrbitMarkdownFooter()
    ].join("\n\n");
  }

  return [
    buildOrbitMarkdownHeader({
      title: `Message Plan: ${plan.program_name}`,
      subtitle: "Internal Orbit planning artifact.",
      logoPath: branding?.assets?.light?.relative ?? null
    }),
    "",
    `- Platform: ${plan.platform}`,
    `- Objective: ${plan.objective}`,
    `- Audience: ${plan.audience}`,
    "",
    "## Messages",
    ...(plan.messages ?? []).map(
      (message) =>
        `- ${message.sequence_order}. ${message.name} (${message.channel}) — ${message.timing} — CTA: ${message.cta}`
    ),
    "",
    "## Dependencies",
    ...(plan.dependencies ?? []).map((dependency) => `- ${dependency}`),
    "",
    "## Personalization Requirements",
    ...(plan.personalization_requirements ?? []).map((field) => `- ${field}`),
    buildOrbitMarkdownFooter()
  ].join("\n");
}

function buildChecklistDoc(plan, branding) {
  return [
    buildOrbitMarkdownHeader({
      title: "Build Checklist",
      subtitle: "Internal Orbit implementation checklist.",
      logoPath: branding?.assets?.light?.relative ?? null
    }),
    "",
    "- Confirm program brief is approved.",
    "- Confirm lifecycle diagram matches the intended journey.",
    "- Generate and compile every email asset.",
    "- QA personalization, links, legal footer, and dark mode.",
    "- Build the Braze pack and verify Content Block dependencies.",
    "- Import this bundle into Notion and assign owners per message.",
    "",
    "## Message-specific Checks",
    ...(plan?.messages ?? []).map(
      (message) => `- ${message.name}: template, QA, preview, and build handoff complete`
    ),
    buildOrbitMarkdownFooter()
  ].join("\n");
}

function buildPreviewDoc(previews, branding) {
  return [
    buildOrbitMarkdownHeader({
      title: "Preview Manifest",
      subtitle: "Internal Orbit preview references for review and handoff.",
      logoPath: branding?.assets?.light?.relative ?? null
    }),
    "",
    ...(previews.length === 0
      ? ["_No preview files supplied._"]
      : previews.flatMap((preview) => [
          `## ${preview.title}`,
          `- Desktop: ${preview.desktop ?? "n/a"}`,
          `- Mobile: ${preview.mobile ?? "n/a"}`,
          `- Dark: ${preview.dark ?? "n/a"}`,
          ""
        ])),
    buildOrbitMarkdownFooter()
  ].join("\n");
}
